web/router.ex
defmodule Handiman.Router do
  use Handiman.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Handiman do
    pipe_through :browser # Use the default browser stack

    get  "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/", PageController, :index
    resources "/users", UserController do
      resources "/rounds", RoundController
    end
    resources "/courses", CourseController do
      resources "/tees", TeeController
    end

  end

  #Other scopes may use custom stacks.
  scope "/api", Handiman do
    pipe_through :api
    get "/course/:id/tees", CourseController, :course_tees
  end
end

web/models/user.ex
defmodule Handiman.User do
  use Handiman.Web, :model

  alias Handiman.Repo

  @differentials %{
    5 => 1,
    6 => 1,
    7 => 2,
    8 =>2,
    9 => 3,
    10 => 3,
    11 => 4,
    12 => 4,
    13 => 5,
    14 => 5,
    15 => 6,
    16 => 6,
    17 => 7,
    18 => 8,
    19 => 9,
    20 => 10
  }

  schema "users" do
    field :name, :string
    field :email, :string
    field :handicap, :integer
    field :encrypted_password, :string
    field :admin, :boolean
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true

    has_many :rounds, Handiman.Round
    timestamps
  end

  @required_fields ~w(name email)
  @optional_fields ~w(handicap password password_confirmation)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
      model
      |> cast(params, @required_fields, @optional_fields)
      |> validate_unique(:email, on: Handiman.Repo, downcase: true)
      |> validate_format(:email, ~r/@/) # TODO more robust email validation
      |> validate_length(:password, min: 5)
      |> validate_confirmation(:password)
  end

  @doc """
  Creates a changeset based on the `model` and `params`. But goes further than changeset as it check if there is a password
  supplied. If so, delegate to changeset to run full validations, otherwise run subset of validations.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def update_changeset(model, params \\ :empty) do
    if params[:password] != "" do
      model
      |> changeset(params)
    else
      model
      |> cast(params, @required_fields, @optional_fields)
      |> validate_unique(:email, on: Handiman.Repo, downcase: true)
      |> validate_format(:email, ~r/@/) # TODO more robust email validation
    end
  end

  @doc """
  Calculate a handicap for the user defined by the user_id. Use the count to determine the number of differentials to
  consider when calculating the handicap.
  """
  def calculate_handicap(count, user_id) do
    if count < 5 do
      {:error, "User needs more rounds before a handicap can be calculated"}
    else
      if count > 20, do: count = 20 # If the number of rounds is greater than 20 just use 20.
      num_differentials = @differentials[count]
      query = from u in Handiman.User,
              join: r in assoc(u, :rounds),
              where: r.user_id == u.id,
              where: u.id == "#{user_id}",
              select: r.differential,
              order_by: [desc: r.inserted_at],
              limit: "#{num_differentials}"
      diffs = Repo.all(query)
      # TODO move sum into query.
      {_, diff_sum} = Enum.map_reduce(diffs, 0, fn(x, acc) -> {x, acc + x} end)
      {:ok, Float.floor((diff_sum/num_differentials) * 0.96, 1)}
    end
  end

  @doc """
  Get the number of rounds a user has.
  """
  def round_count(user_id) do
    query = from u in Handiman.User, join: r in assoc(u, :rounds), where: r.user_id == "#{user_id}", select: count(r.id)
    Repo.one(query)
  end

  def with_preloaded_assoc(user_id) do
    query = from u in Handiman.User,
            join: r in assoc(u, :rounds),
            join: t in assoc(r, :tee),
            join: c in assoc(t, :course),
            where: u.id == "#{user_id}", preload: [rounds: {r, tee: {t, course: c}}]
    Repo.one(query)
  end
end

web/controllers/user_controller.ex
defmodule Handiman.UserController do
  use Handiman.Web, :controller

  alias Handiman.User

  plug :scrub_params, "user" when action in [:create, :update]

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    changeset = Handiman.Round.changeset(%Handiman.Round{})
    user = User.with_preloaded_assoc(id)
    {courses, tees} = retrieve_courses_and_tees
    case User.round_count(id) |> User.calculate_handicap(id) do
      {:ok, handicap} -> render(conn, "show.html", changeset: changeset, user: user, handicap: handicap, courses: courses, tees: tees)
      {:error, error} ->
        conn
          |> put_flash(:info, error)
          |> render("show.html",changeset: changeset, user: user, handicap: "N/A", courses: courses, tees: tees)
    end
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    changeset = User.update_changeset(user, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end

  defp retrieve_courses_and_tees() do
    course_query = from c in Handiman.Course, select: %{"course_id"=>c.id, "course_name"=>c.name}
    tee_query = from t in Handiman.Tee, select: %{"tee_id"=>t.id, "course_id"=>t.course_id}
    tees = Repo.all(tee_query)
    courses = Repo.all(course_query)
    {courses, tees}
  end
end

web/views/user_view.ex
defmodule Handiman.UserView do
  use Handiman.Web, :view


    def course_names([head | tail], names \\ []), do: _course_names([head | tail], names)
    defp _course_names([], names), do: List.flatten(names)
    defp _course_names([head | tail], names), do: _course_names(tail, [names, [head["course_name"], head["course_id"]]])
end

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, "Name", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :email, "Email", class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :handicap, "Handicap", class: "control-label" %>
    <%= number_input f, :handicap, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :password, "Password", class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, "Password Confirmation", class: "control-label" %>
    <%= password_input f, :password_confirmation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Handicap</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.handicap %></td>

      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

web/templates/user/new.html.eex
<h2>New user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :create) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/show.html.eex
<div class="fluid-container col-sm-10 col-sm-offset-1 well">
    <div class="row">
        <div class="col-sm-9"><h1> <%= @user.name %></h1></div>
        <div class="col-sm-3"><h1 class="pull-right"> Handicap: <%= @handicap %></h1></div>
    </div>
    <div class="row">
        <div class="col-sm-3"><!--left col-->

            <ul class="list-group">
                <li class="list-group-item text-muted">Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> <%=
                    @user.inserted_at %>
                </li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Email</strong></span> <%=
                    @user.email %>
                </li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Handicap</strong></span> <%=
                    @handicap %>
                </li>
            </ul>


            <ul class="list-group">
                <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Rounds</strong></span> <%=
                    Enum.count(@user.rounds) %>
                </li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Rounds under par</strong></span>
                    0
                </li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Posts</strong></span> 37</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Followers</strong></span> 78</li>
            </ul>

        </div>
        <!--/col-3-->
        <div class="col-sm-9">
            <div class="table-responsive">
                <table class="table table-hover">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Course</th>
                            <th>Score</th>
                            <th>Holes</th>
                            <th>Tee</th>
                            <th>Course Rating</th>
                            <th>Slope Rating</th>
                            <th>Differential</th>
                        </tr>
                        </thead>
                        <tbody>
                        <%= for round <- @user.rounds do %>
                        <tr>
                            <td id="course_name"><%= round.tee.course.name %></td>
                            <td id="score"><%= round.score %></td>
                            <td id="holes"><%= round.holes %></td>
                            <td id="tee_name"><%= round.tee.name %></td>
                            <td id="course_rating"><%= round.tee.usga_course_rating %></td>
                            <td id="slope_rating"><%= round.tee.slope_rating %></td>
                            <td id="differential"><%= round.differential %></td>

                            <td class="text-right">
                                <button class="btn btn-primary btn-xs" id="editButton" data-toggle="modal" data-target="#editRoundModal">
                                    Edit
                                </button>
                                <%= link "Delete", to: user_round_path(@conn, :delete, current_user(@conn), round),
                                method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
                            </td>
                        </tr>
                        <% end %>
                        </tbody>
                    </table>
                </table>
                <hr>
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 text-center">
                        <ul class="pagination" id="myPager"></ul>
                    </div>
                </div>
            </div>
            <!--/table-resp-->
            <hr>
            <!-- Button trigger modal -->
            <button class="btn btn-primary btn-sm pull-right" data-toggle="modal" data-target="#addRoundModal">
                add round
            </button>

            <!-- Modal -->
            <div class="modal fade" id="addRoundModal" tabindex="-1" role="dialog"
                 aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <!-- Modal Header -->
                        <div class="modal-header">
                            <button type="button" class="close"
                                    data-dismiss="modal">
                                <span aria-hidden="true">&times;</span>
                                <span class="sr-only">Close</span>
                            </button>
                            <h4 class="modal-title" id="myModalLabel">
                                Add a round
                            </h4>
                        </div>

                        <!-- Modal Body -->
                        <div class="modal-body">

                            <%= form_for @changeset, user_round_path(@conn, :create, current_user(@conn)), fn f -> %>
                            <%= if @changeset.action do %>
                            <div class="alert alert-danger">
                                <p>Oops, something went wrong! Please check the errors below:</p>
                                <ul>
                                    <%= for {attr, message} <- f.errors do %>
                                    <li><%= humanize(attr) %> <%= message %></li>
                                    <% end %>
                                </ul>
                            </div>
                            <% end %>

                            <div class="form-group">
                                <%= label f, :score, "Score", class: "control-label" %>
                                <%= number_input f, :score, class: "form-control" %>
                            </div>

                            <div class="form-group">
                                <%= label f, :holes, "Holes", class: "control-label" %>
                                <%= select f, :holes, [9, 18], class: "form-control", default: 18 %>
                            </div>

                            <div class="form-group">
                                <%= label f, :holes, "Where did you play?", class: "control-label" %>
                                <%= select f, :course_name, course_names(@courses), prompt: "Course", class:
                                "form-control" %>
                            </div>

                            <div class="form-group">
                                <%= label f, :holes, "What tee did you play from?", class: "control-label" %></br>
                                <%= select f, :tee_id, [], prompt: "Tee", class: "form-control" %>
                            </div>

                            <!-- Modal Footer -->
                            <div class="modal-footer">
                                <div class="form-group">
                                    <%= submit "Submit", class: "btn btn-primary" %>
                                </div>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal fade" id="editRoundModal" tabindex="-1" role="dialog"
                 aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <!-- Modal Header -->
                        <div class="modal-header">
                            <button type="button" class="close"
                                    data-dismiss="modal">
                                <span aria-hidden="true">&times;</span>
                                <span class="sr-only">Close</span>
                            </button>
                            <h4 class="modal-title" id="myModalLabel">
                                Edit round details
                            </h4>
                        </div>

                        <!-- Modal Body -->
                        <div class="modal-body">
                            <%= form_for @changeset, user_round_path(@conn, :create, current_user(@conn)), fn f -> %>
                            <%= if @changeset.action do %>
                            <div class="alert alert-danger">
                                <p>Oops, something went wrong! Please check the errors below:</p>
                                <ul>
                                    <%= for {attr, message} <- f.errors do %>
                                    <li><%= humanize(attr) %> <%= message %></li>
                                    <% end %>
                                </ul>
                            </div>
                            <% end %>

                            <div class="form-group">
                                <%= label f, :score, "Score", class: "control-label" %>
                                <%= number_input f, :score, class: "form-control" %>
                            </div>

                            <div class="form-group">
                                <%= label f, :holes, "Holes", class: "control-label" %>
                                <%= select f, :holes, [9, 18], class: "form-control", default: 18 %>
                            </div>

                            <div class="form-group">
                                <%= label f, :holes, "Where did you play?", class: "control-label" %>
                                <%= select f, :course_name, course_names(@courses), prompt: "Course", class:
                                "form-control" %>
                            </div>

                            <div class="form-group">
                                <%= label f, :holes, "What tee did you play from?", class: "control-label" %></br>
                                <%= select f, :tee_id, [], prompt: "Tee", class: "form-control" %>
                            </div>

                            <!-- Modal Footer -->
                            <div class="modal-footer">
                                <div class="form-group">
                                    <%= submit "Submit", class: "btn btn-primary" %>
                                </div>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
        </div>
        <!--/col-9-->
    </div>
    <!--/row-->
</div>
<script type="text/javascript">

    function setupCourseSelect() {
        var courseSelect = document.getElementById('round_course_name');
        var courses = new Object();
        for (i = 1; i < courseSelect.length; i += 2) {
            courses[courseSelect.options[i].value] = courseSelect.options[i + 1].value;
        }
        course_keys = Object.keys(courses);
        // Clear out the options
        var i;
        for (i = courseSelect.options.length - 1; i >= 1; i--) {
            courseSelect.remove(i);
        }

        // Add new options
        for (var i = 0; i < course_keys.length; ++i) {
            var key = course_keys[i]
            var opt = document.createElement('option');
            opt.value = courses[key];
            opt.innerHTML = key;
            courseSelect.appendChild(opt);
        }
        courseSelect.onchange = send_request;
    }

    function send_request() {
        var course_id = $('#round_course_name').find(":selected").val();
        var url = location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '');
        $.ajax({
            type: "GET",
            url: url + "/api/course/" + course_id + "/tees",
            cache: false,
            success: function (data) {
                var select = document.getElementById('round_tee_id');

                // Clear out the options
                var i;
                for (i = select.options.length - 1; i >= 0; i--) {
                    select.remove(i);
                }

                // Add new options
                for (var i = 0; i < data.length; ++i) {
                    var opt = document.createElement('option');
                    opt.value = data[i].id;
                    opt.innerHTML = data[i].name;
                    select.appendChild(opt);
                }
            }
        });
    }
    document.onload = setupCourseSelect();
</script>